feat: add exit codes to the library
Adds exit codes to all the errors in the library that are
generated with the logging module.

This feature was added as part of the challenge of including
the exit code in the error messages by using bash.

This is an example of joining the exit code with the error message:
'Error code 5: Attempted to downgrade from basic to premium.'

Other changes:
- Adds an 'exit_code' attribute to the SubscriptionManager
class to store the exit code on error.
- Includes all the necessary unit tests.
- Modifies some tests to fit this new feature.
- Modifies the logging module configuration to send the
errors to a file.
- Creates the file error.log that the logging module will
use to write the errors.
- Modifies the cli file to join the exit code with the
error message.

Additional notes:
- The meaning of each exit code will be included later
in the README.md file of the library.

diff --git a/02_your_code/cli b/02_your_code/cli
--- a/02_your_code/cli
+++ b/02_your_code/cli
@@ -8,21 +8,41 @@ fi
 
 if [ "upgrade" == $1 ]; then
     echo "Upgrading with args: ${@:2}"
+
     if [ -z "$2" ] || [ -z "$3" ]; then
     echo "Error: missing arguments uuid and/or plan"
     exit 1;
     fi
+
     python run_subs_manager.py upgrade $2 $3
+    exit_code=$?
+
+    if [ $exit_code != 0 ]; then
+    error=$(< error.log)
+    echo "Error code $exit_code: $error"
+    exit $exit_code
+    fi
+
     exit;
 fi
 
 if [ "downgrade" == $1 ]; then
     echo "Downgrading with args: ${@:2}"
+
     if [ -z "$2" ] || [ -z "$3" ]; then
     echo "Error: missing arguments uuid and/or plan"
     exit 1;
     fi
+
     python run_subs_manager.py downgrade $2 $3
+    exit_code=$?
+
+    if [ $exit_code != 0 ]; then
+    error=$(< error.log)
+    echo "Error code $exit_code: $error"
+    exit $exit_code
+    fi
+
     exit;
 fi
 
