feat: create a library to manage subscriptions
This library allows managing the customer
subscriptions that are stored in the customerdataapi
microservice.

Provides a class called UpgradeSubscription
for upgrading the subscription level in the
configuration data of a specific customer.

It also provides a class called DowngradeSubscription
for downgrading the subscription level in the
configuration data of a specific customer.

diff --git a/02_your_code/cli b/02_your_code/cli
--- a/02_your_code/cli
+++ b/02_your_code/cli
@@ -9,13 +9,21 @@ fi
 
 if [ "upgrade" == $1 ]; then
     echo "Upgrading with args: ${@:2}"
-    # Use this line to call your code
+    if [ -z "$2" ] || [ -z "$3" ]; then
+    echo "Error: missing arguments uuid and/or plan"
+    exit 1;
+    fi
+    python run_subs_manager.py upgrade $2 $3
     exit;
 fi
 
 if [ "downgrade" == $1 ]; then
     echo "Downgrading with args: ${@:2}"
-    # Use this line to call your code
+    if [ -z "$2" ] || [ -z "$3" ]; then
+    echo "Error: missing arguments uuid and/or plan"
+    exit 1;
+    fi
+    python run_subs_manager.py downgrade $2 $3
     exit;
 fi
 
